### ISSUE TITLE
Demo is broken

### ISSUE THREAD

**Issue by batje** [se-panfilov/mini-toastr#127]
The index.html file in the demo points to 

`<script src="bower_components/mini-toastr/dist/mini-toastr.es5.js" defer></script>`

but that file does not exist, hence the demo does not work.

**Comment by kinglisky** [comment]
Me too.

![image](https://user-images.githubusercontent.com/15852576/33674227-d85c282c-dae9-11e7-993b-dfe1cde661a1.png)

**Comment by se-panfilov** [comment]
Fixed!

@batje, @kinglisky  thanks, guys!
